[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
exclude = """src/c_syntax_validator/parser|build"""

[tool.isort]
profile = "black"
extend_skip = ["src/c_syntax_validator/parser"]
